src/Identity_Authorization_Security/ContactsManagerSolution/ContactsManager.UI/Controllers/CountriesController.cs
using ContactsManager.Core.ServiceContracts;
using Microsoft.AspNetCore.Mvc;

namespace ContactsManager.UI.Controllers
{
    [Route("[controller]")]

    public class CountriesController : Controller
    {
        private readonly ICountriesUploaderService _countriesUploaderService;

        public CountriesController(ICountriesUploaderService countriesUploaderService)
        {
            _countriesUploaderService = countriesUploaderService;
        }

        [HttpGet]
        [Route("[action]")]
        public IActionResult UploadFromExcel()
        {
            return View();
        }

        [HttpPost]
        [Route("[action]")]
        public async Task<IActionResult> UploadFromExcel(IFormFile? excelFile)
        {
            if (excelFile == null || excelFile.Length == 0)
            {
                ViewBag.ErrorMessage = "Please select an xlsx file";
                return View();
            }

            if (!Path.GetExtension(excelFile.FileName).Equals(".xlsx", StringComparison.OrdinalIgnoreCase))
            {
                ViewBag.ErrorMessage = "Unsupported file. 'xlsx' file is expected";
                return View();
            }

            int countriesCountInserted = await _countriesUploaderService.UploadCountriesFromExcelFile(excelFile);

            ViewBag.Message = $"{countriesCountInserted} Countries Uploaded";
            return View();
        }
    }
}

src/Identity_Authorization_Security/ContactsManagerSolution/ContactsManager.UI/Views/Countries/UploadFromExcel.cshtml
@{
    ViewBag.Title = "Upload Countries from Excel";
    ViewBag.CurrentUrl = "~/Countries/UploadFromExcel";
}
<div class="flex">
    <div class="flex-1">
        <span class="text-grey">Contacts</span>
        <i class="fa-solid fa-caret-right"></i>
        <span class="text-grey">Countries</span>
        <i class="fa-solid fa-caret-right"></i>
        <span class="text-grey">Upload</span>
    </div>
</div>

<div class="form-container">
    <h2 class="text-large">Upload Countries from Excel</h2>
    <div class="w-50">
        <form asp-action="UploadFromExcel" asp-controller="Countries" method="post" enctype="multipart/form-data">
            @*         Excel File*@
            <div class="form-field flex">
                <div class="w-25">
                    <label class="form-label pt">Choose an xlsx file</label>
                </div>

                <div class="flex-1">
                    <input type="file" name="excelFile" class="form-input" />
                    <div class="text-red">@ViewBag.ErrorMessage</div>
                    <div class="text-green">@ViewBag.Message</div>
                </div>
            </div>

            <div class="form-field flex">
                <div class="w-25"></div>
                <div class="flex-1">
                    <button type="submit" class="button button-green-back">Upload</button>
                </div>
            </div>
        </form>
    </div>
</div>