src/Clean_Architecture/StocksAppSolution/StocksAppSolution/Controllers/StocksController.cs
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using StocksApp.Core.ServiceContracts;
using StocksApp.UI.Models;

namespace StocksApp.UI.Controllers
{
    [Route("[controller]")]
    public class StocksController : Controller
    {
        private readonly IFinnhubStocksService _finnhubStocksService;
        private readonly IFinnhubSearchStocksService _finnhubSearchStocksService;
        private readonly IOptions<TradingOptions> _tradingOptions;
        private readonly ILogger<StocksController> _logger;

        public StocksController(IFinnhubStocksService finnhubStocksService, IFinnhubSearchStocksService finnhubSearchStocksService, IOptions<TradingOptions> tradingOptions, ILogger<StocksController> logger)
        {
            _finnhubStocksService = finnhubStocksService;
            _finnhubSearchStocksService = finnhubSearchStocksService;
            _tradingOptions = tradingOptions;
            _logger = logger;
        }

        [Route("[action]/{stock?}")]
        [Route("/")]
        [HttpGet]
        public async Task<IActionResult> Explore(string? searchBy, string? stock, bool showAll = false, int pg=1)
        {
            if (stock != null) ViewBag.stock = stock;
            List<Stock> stocks = new List<Stock>();


            if (string.IsNullOrEmpty(searchBy))
            {
                _logger.LogDebug("Explore Action Method with searchBy");
                List<string>? popularStocks = _tradingOptions.Value.Top25PopularStocks?.Split(",").ToList();

                var stockResults = await _finnhubStocksService.GetStocks();
                if (stockResults != null)
                {
                    if (showAll == false)
                    {
                        stockResults = stockResults.FindAll(temp => popularStocks != null && popularStocks.Contains(temp["displaySymbol"]));
                    }
                    else
                    {
                        const int pageSize = 20;
                        if (pg < 1)
                        {
                            pg = 1;
                        }

                        int recsCount = stockResults.Count();

                        var pager = new Pager(recsCount, pg, pageSize);
                        int recSkip = (pg -1 ) * pageSize;

                        stockResults = stockResults.Skip(recSkip).Take(pager.PageSize).ToList();
                        ViewBag.Pager = pager;
                    }

                    foreach (var obj in stockResults)
                    {
                        stocks.Add(new Stock
                        {
                            StockName = obj["description"],
                            StockSymbol = obj["displaySymbol"]
                        });
                    }

                }
            }

            else
            {
                _logger.LogDebug("Explore Action Method without searchBy");

                Dictionary<string, object>? stocksFromSearchStocks = await _finnhubSearchStocksService.SearchStocks(searchBy);
                if (stocksFromSearchStocks != null)
                {
                    JsonElement stocksFromSearchJsonElement = (JsonElement)stocksFromSearchStocks["result"];
                    List<Dictionary<string, object>>? stocksFromSearchList =
                        JsonSerializer.Deserialize<List<Dictionary<string, object>>>(stocksFromSearchJsonElement.GetRawText());

                    if (stocksFromSearchList != null)
                        foreach (Dictionary<string, object> stockItem in stocksFromSearchList)
                        {
                            stocks.Add(new Stock() { StockName = stockItem["description"].ToString(), StockSymbol = stockItem["symbol"].ToString() });
                        }
                }
            }

            return View(stocks);

        }
    }
}

src/Clean_Architecture/StocksAppSolution/StocksAppSolution/Controllers/TradeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Rotativa.AspNetCore;
using Rotativa.AspNetCore.Options;
using StocksApp.Core.DTO;
using StocksApp.Core.ServiceContracts;
using StocksApp.UI.Filters.ActionFilters;
using StocksApp.UI.Models;

namespace StocksApp.UI.Controllers
{
    [Route("[controller]")]
    public class TradeController : Controller
    {
        private readonly IFinnhubCompanyProfileService _finnhubCompanyProfileService;
        private readonly IFinnhubStockPriceQuoteService _finnhubStockPriceQuoteService;
        private readonly IOptions<TradingOptions> _tradingOptions;
        private readonly IStocksService _stocksService;
        private readonly ILogger<TradeController> _logger;

        public TradeController(IFinnhubCompanyProfileService finnhubCompanyProfileService, IFinnhubStockPriceQuoteService finnhubStockPriceQuoteService, IOptions<TradingOptions> tradingOptions, IStocksService stocksService, ILogger<TradeController> logger)
        {
            _finnhubCompanyProfileService = finnhubCompanyProfileService;
            _finnhubStockPriceQuoteService = finnhubStockPriceQuoteService;
            _tradingOptions = tradingOptions;
            _stocksService = stocksService;
            _logger = logger;
        }

        [Route("[action]/{stockSymbol?}/")]
        public async Task<IActionResult> Index(string? stockSymbol = "MSFT")
        {
            _logger.LogDebug($"Index action method from trade controller. stockSymbol = {stockSymbol}");
            Dictionary<string, object>? companyProfileDictionary = 
                await _finnhubCompanyProfileService.GetCompanyProfile(stockSymbol);
            Dictionary<string, object?>? stockPriceQuoteDictionary = 
                await _finnhubStockPriceQuoteService.GetStockPriceQuote(stockSymbol);

            StockTrade stockTrade = new StockTrade()
            {
                Price = Convert.ToDouble(stockPriceQuoteDictionary?["c"].ToString()),
                StockName = companyProfileDictionary?["name"].ToString(),
                StockSymbol = companyProfileDictionary?["ticker"].ToString()
            }; 
            return View(stockTrade);
        }

        [Route("[action]")]
        [HttpPost]
        [TypeFilter(typeof(CreateOrderActionFilter))]
        public async Task<IActionResult> BuyOrder(BuyOrderRequest orderRequest)
        {
            _logger.LogDebug($"BuyOrder action method from trade controller. orderRequest = {orderRequest.StockName}: {orderRequest.Quantity}");

            orderRequest.DateAndTimeOfOrder = DateTime.Now;

            await _stocksService.CreateBuyOrder(orderRequest);
            return RedirectToAction(nameof(Orders));
        }

        [Route("[action]")]
        [HttpPost]
        [TypeFilter(typeof(CreateOrderActionFilter))]
        public async Task<IActionResult> SellOrder(SellOrderRequest orderRequest)
        {
            _logger.LogDebug($"SellOrder action method from trade controller. orderRequest = {orderRequest.StockName}: {orderRequest.Quantity}");

            orderRequest.DateAndTimeOfOrder = DateTime.Now;

            await _stocksService.CreateSellOrder(orderRequest);
            return RedirectToAction(nameof(Orders));
        }

        [Route("[action]")]
        [HttpGet]
        public async Task<IActionResult> Orders()
        {
            _logger.LogDebug("Orders action method from tradeController");
            List<BuyOrderResponse> buyOrderResponses = await _stocksService.GetBuyOrders();
            List<SellOrderResponse> sellOrderResponses = await _stocksService.GetSellOrders();

            Orders orders = new Orders()
            {
                BuyOrders = buyOrderResponses,
                SellOrders = sellOrderResponses
            };
            return View(orders);
        }

        [Route("[action]")]
        public async Task<IActionResult> OrdersPDF()
        {
            _logger.LogDebug("OrdersPDF action method from tradeController");

            List<BuyOrderResponse>? buyOrders = await _stocksService.GetBuyOrders();
            List<SellOrderResponse>? sellOrder = await _stocksService.GetSellOrders();
            Orders orders = new Orders() { BuyOrders = buyOrders, SellOrders = sellOrder };
            return new ViewAsPdf("OrdersPDF", orders, ViewData)
            {
                PageMargins = new Margins() { Top = 20, Bottom = 20, Left = 20, Right = 20},
                PageOrientation = Orientation.Landscape
            };
        }


        [Route("/api/v1/StockPriceQuote")]
        public async Task<IActionResult> GetStockPriceQuote([FromQuery] string? stockSymbol)
        {
            _logger.LogDebug("GetStockPriceQuote action method from tradeController");

            if (stockSymbol == null)
            {
                return NotFound();
            }

            Dictionary<string, object?>? companyProfileDictionary = 
                await _finnhubStockPriceQuoteService.GetStockPriceQuote(stockSymbol);

            return Json(companyProfileDictionary);
        }
    }
}

src/Clean_Architecture/StocksAppSolution/StocksAppSolution/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title | Stocks</title>
    <link href="~/StyleSheet.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
        <div class="page-content">
            <div class="margin-bottom">
                <div class="flex" id="top-bar-div">
                    <div class="flex-1" id="app-title-div">
                        <h1 class="app-title">
                            <i class="fa-solid fa-money-bill-trend-up"></i>
                            Stocks
                        </h1>
                    </div>

                    <div class="flex-2 pr" id="search-box-div">
                        <form asp-controller="Stocks" method="get" asp-action="Explore">
                            <input name="searchBy" class="search-text" placeholder="Search Stocks" />
                            <button class="button button-blue-back ml login-button" type="submit">Search</button>
                        </form>
                        <i class="fa-solid fa-gear"></i>

                        <button class="button button-blue-back ml login-button">Login</button>
                    </div>
                </div>

            </div>


            <div class="navbar mb">
                <ul>
                    @if (ViewBag.CurrentUrl == "~/Trade/Index")
                    {
                        <li><a asp-controller="Trade" asp-action="Index" class="nav-active">Trade</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="Trade" asp-action="Index">Trade</a></li>
                    }

                    @if (ViewBag.CurrentUrl == "~/Trade/Orders")
                    {
                        <li><a asp-controller="Trade" asp-action="Orders" class="nav-active">Orders</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="Trade" asp-action="Orders">Orders</a></li>
                    }

                    @if (ViewBag.CurrentUrl == "~/Stocks/Explore")
                    {
                        <li><a asp-controller="Stocks" asp-action="Explore" class="nav-active">Explore</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="Stocks" asp-action="Explore">Explore</a></li>
                    }

                    <li><a asp-controller="Trade" asp-action="OrdersPDF">Download as PDF</a></li>
                </ul>
            </div>

            @RenderBody()
        </div>

    </div>

    @await RenderSectionAsync("scripts", required: false)

</body>
</html>