src/ViewComponents/ViewComponentsExample/Models/Person.cs
namespace ViewComponentsExample.Models
{
    public class Person
    {
        public string? PersonName { get; set; }
        public string? JobTitle { get; set; }
    }
}

src/ViewComponents/ViewComponentsExample/Models/PersonGridModel.cs
namespace ViewComponentsExample.Models
{
    public class PersonGridModel
    {
        public string GridTitle { get; set; } = string.Empty;
        public List<Person> People { get; set; } = new List<Person>();
    }
}

src/ViewComponents/ViewComponentsExample/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ViewComponentsExample.Models;

namespace ViewComponentsExample.Controllers
{
    public class HomeController : Controller
    {
        [Route("/")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("about")]
        public IActionResult About()
        {
            return View();
        }

        [Route("friends-list")]
        public IActionResult LoadFriendsList()
        {
            PersonGridModel personGridModel2 = new PersonGridModel()
            {
                GridTitle = "Friends",
                People = new List<Person>()
                {
                    new Person() { PersonName = "Mia", JobTitle = "Developer" },
                    new Person() { PersonName = "Emma", JobTitle = "UI" },
                    new Person() { PersonName = "Avva", JobTitle = "QA" },
                }
            };

            return new ViewComponentResult()
                { ViewComponentName = "Grid", Arguments = new { grid = personGridModel2 } }; 
        }
    }
}

src/ViewComponents/ViewComponentsExample/ViewComponents/GridViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ViewComponentsExample.Models;

namespace ViewComponentsExample.ViewComponents
{
    [ViewComponent]
    public class GridViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(PersonGridModel grid)
        {
            return View("Sample", grid); //invoked a partial view Views/Shared/Components/Grid/Sample.cshtml
        }
    }
}

src/ViewComponents/ViewComponentsExample/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<h1>About</h1>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

@{
    PersonGridModel personGridModel1 = new PersonGridModel()
    {
        GridTitle = "Employees",
        People = new List<Person>()
        {
            new Person() { PersonName = "Sarath", JobTitle = "Developer" },
            new Person() { PersonName = "Srinivas", JobTitle = "UI" },
            new Person() { PersonName = "Varun", JobTitle = "QA" },
        }
    };
}
<vc:grid grid="personGridModel1"></vc:grid>

src/ViewComponents/ViewComponentsExample/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<h1>Home</h1>

<button class="button button-blue-back" id="load-friends-button">Load Friends</button>

<div id="list">

</div>

<script src="/friends.js"></script>

src/ViewComponents/ViewComponentsExample/Views/Shared/Components/Grid/Sample.cshtml
@model PersonGridModel
<div class="box">
    <h3>@Model.GridTitle</h3>
    <table class="table w-100">
        <thead>
            <tr>
                <th>Sl. No</th>
                <th>Name</th>
            </tr>
        </thead>

        <tbody>
        @foreach (Person person  in Model.People)
        {
            <tr>
                <td>@person.PersonName</td>
                <td>@person.JobTitle</td>
            </tr>
        }
        </tbody>
    </table>
</div>